localStorage.setItem('Token','ugu87uguyf76yug')
undefined
localStorage.getItem('Token')
"ugu87uguyf76yug"
localStorage.setItem('_i9iihjh','kjekjfnjkdbkj')
undefined
localStorage.getItem('_i9iihjh')
"kjekjfnjkdbkj"
localStorage.removeItem('Token')
undefined
localStorage.getItem('Token')
null
localStorage.key(0)
"_i9iihjh"
localStorage.key(1)
"nkjjd"
localStorage.key(2)
"Token1"
localStorage.length
3